import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import express from 'express';
import { openDatabase } from '../server/db.js';
import { seed } from '../server/seed.js';
import { createApp } from '../server/app.js';
mkdirSync('test-results',{recursive:true});
const temp=mkdtempSync(join(tmpdir(),'urbana-field-browser-'));
process.env.DATA_DIR=temp;process.env.DEMO_DATA='true';process.env.ADMIN_PASSWORD='Urbana@2026';delete process.env.DATABASE_URL;
const db=await openDatabase();await seed(db);
const app=createApp(db);app.use(express.static(resolve('dist')));app.get('/{*path}',(req,res)=>res.sendFile(resolve('dist/index.html')));
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,channel:'msedge'});
const errors=[];
const login=async(page,email)=>{await page.getByLabel('E-mail',{exact:true}).fill(email);await page.getByLabel('Senha',{exact:true}).fill('Urbana@2026');await page.getByRole('button',{name:'Entrar',exact:true}).click();};
const photo={name:'evidencia-teste.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jV6kAAAAASUVORK5CYII=','base64')};
try {
 const fieldContext=await browser.newContext({viewport:{width:390,height:844},geolocation:{latitude:-30.1,longitude:-48.6},permissions:['geolocation']});
 const field=await fieldContext.newPage();field.on('pageerror',e=>errors.push(e.message));
 await field.goto(url+'/campo');await login(field,'campo@urbana.local');await field.getByRole('heading',{name:'Minhas tarefas',exact:true}).waitFor();
 assert.equal(await field.locator('.sidebar').count(),0);
 await field.evaluate(()=>navigator.serviceWorker.ready.then(()=>undefined));
 await field.getByRole('button',{name:'Registrar',exact:true}).click();
 await field.route('**/findAddressCandidates?*', async route => {
   const query = new URL(route.request().url()).searchParams.get('SingleLine');
   if(query === 'Falha de rede') return route.abort();
   return route.fulfill({json:{candidates:query === 'Rua inexistente' ? [] : [{address:'Rua Teste, 123, Cidade',location:{x:-48.6,y:-30.1},attributes:{Neighborhood:'Centro'}}]}});
 });
 const addressSearch=field.getByRole('searchbox',{name:'Buscar endere\u00e7o'});
 await addressSearch.fill('Rua inexistente');await addressSearch.press('Enter');
 await field.getByRole('status').filter({hasText:'Nenhum endere\u00e7o encontrado'}).waitFor();
 await addressSearch.fill('Falha de rede');await addressSearch.press('Enter');
 await field.getByRole('status').filter({hasText:'Verifique a conex\u00e3o'}).waitFor();
 await addressSearch.fill('Rua Teste, 123, Cidade');await addressSearch.press('Enter');
 await field.getByRole('button',{name:'Rua Teste, 123, Cidade',exact:true}).click();
 assert.equal(await field.getByLabel('Rua e n\u00famero',{exact:true}).inputValue(),'Rua Teste, 123, Cidade');
 assert.equal(await field.getByLabel('Bairro',{exact:true}).inputValue(),'Centro');
 assert.equal(await field.getByLabel('Latitude do registro',{exact:true}).inputValue(),'-30.1');
 assert.equal(await field.getByLabel('Longitude do registro',{exact:true}).inputValue(),'-48.6');
 assert.equal(await field.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await field.getByLabel('Foto do problema',{exact:true}).setInputFiles(photo);
 await field.getByRole('button',{name:'Usar minha localização',exact:true}).click();
 await field.getByText('Localização definida:',{exact:false}).waitFor();
 await field.getByLabel('Rua e número',{exact:true}).fill('Rua Operação de Campo, 500');
 await field.getByLabel('Bairro',{exact:true}).fill('Centro');
 await field.getByLabel('Próximo a / ponto de referência',{exact:true}).fill('Próximo à escola municipal');
 await fieldContext.setOffline(true);
 await field.getByLabel('Descrição do problema',{exact:true}).fill('Buraco na pista. Registrar sinalização e reparar o pavimento.');
 await field.getByText('Rascunho salvo neste aparelho.',{exact:false}).waitFor();
 await field.waitForTimeout(600);
 await fieldContext.setOffline(false);await field.reload();await field.getByRole('heading',{name:'Minhas tarefas',exact:true}).waitFor();
 await field.getByRole('button',{name:'Registrar',exact:true}).click();
 await field.getByLabel('Rua e número',{exact:true}).waitFor();
 assert.equal(await field.getByLabel('Rua e número',{exact:true}).inputValue(),'Rua Operação de Campo, 500');
 assert.equal(await field.getByLabel('Descrição do problema',{exact:true}).inputValue(),'Buraco na pista. Registrar sinalização e reparar o pavimento.');
 assert.equal(await field.getByAltText('Foto selecionada para envio').count(),1);
 await field.screenshot({path:'test-results/field-register.png',fullPage:true});
 await field.route('**/api/ocorrencias/*/anexos',route=>route.abort(),{times:1});
 await field.getByRole('button',{name:'Enviar ocorrência',exact:true}).click();
 await field.getByRole('button',{name:'Reenviar foto',exact:true}).waitFor();
 await field.getByRole('button',{name:'Reenviar foto',exact:true}).click();
 await field.getByRole('heading',{name:'Meus registros',exact:true}).waitFor();
 const registered=await (await field.request.get(url+'/api/campo')).json();
 const occurrence=registered.records.find(o=>o.address==='Rua Operação de Campo, 500');assert.ok(occurrence);assert.equal(registered.records.filter(o=>o.address===occurrence.address).length,1);
 const adminContext=await browser.newContext({viewport:{width:1440,height:1000}}),admin=await adminContext.newPage();admin.on('pageerror',e=>errors.push(e.message));await admin.goto(url);await login(admin,'admin@urbana.local');await admin.getByRole('heading',{name:'Visão geral',exact:true}).waitFor();
 assert.equal((await admin.request.post(url+`/api/ocorrencias/${occurrence.id}/classificar`,{data:{category_id:'category-1',subcategory:'Buraco',priority:'Alta',sector_id:'sector-1'}})).status(),200);
 const result=await admin.request.post(url+'/api/ordens-servico',{data:{occurrence_ids:[occurrence.id],team_id:'team-1',scheduled_at:'2026-09-21',responsible:'Equipe de pavimentação',notes:'Sinalizar a via antes do reparo.'}});assert.equal(result.status(),200);const order=await result.json();
 await admin.reload();await admin.locator('nav').getByRole('button',{name:'Ordens de serviço',exact:true}).click();await admin.locator('tbody tr').filter({hasText:order.code}).click();
 await admin.getByText('Distribuir para equipe ou operador',{exact:true}).click();
 await admin.getByLabel('Operador da programação',{exact:true}).selectOption('campo');
 await admin.getByLabel('Instruções para o operador',{exact:true}).fill('Sinalizar a via, executar tapa-buraco e limpar o local.');
 await admin.getByRole('button',{name:'Salvar distribuição',exact:true}).click();
 await admin.waitForResponse(r=>r.url().endsWith('/api/ordens-servico/'+order.id) && r.status()===200);
 assert.equal((await (await admin.request.get(url+'/api/ordens-servico/'+order.id)).json()).assigned_user_id,'campo');
 await field.getByRole('button',{name:'Tarefas',exact:true}).click();await field.getByRole('button',{name:'Atualizar tarefas',exact:true}).click();
 await field.locator('.operator-task').filter({hasText:order.code}).waitFor();await field.screenshot({path:'test-results/field-tasks.png',fullPage:true});
 await field.locator('.operator-task').filter({hasText:order.code}).click();await field.getByRole('heading',{name:order.code,exact:true}).waitFor();
 assert.ok((await field.getByRole('link',{name:'Como chegar',exact:true}).getAttribute('href')).includes('destination=-30.1,-48.6'));
 await field.getByRole('button',{name:'Estou a caminho',exact:true}).click();await field.getByText('A caminho',{exact:true}).waitFor();
 await field.getByRole('button',{name:'Capturar GPS do local',exact:true}).click();await field.getByText('GPS: -30.10000, -48.60000',{exact:true}).waitFor();
 await field.getByLabel('Foto antes',{exact:true}).setInputFiles(photo);await field.getByRole('button',{name:'Enviar foto antes',exact:true}).click();await field.getByText('✓ Foto enviada',{exact:true}).waitFor();
 await field.getByRole('button',{name:'Confirmar chegada e iniciar serviço',exact:true}).click();await field.getByRole('heading',{name:'Materiais utilizados',exact:true}).waitFor();
 await field.getByLabel('Material utilizado',{exact:true}).selectOption('material-1');await field.getByLabel('Quantidade utilizada',{exact:true}).fill('25');await field.getByRole('button',{name:'Adicionar material',exact:true}).click();
 await field.getByLabel('O que foi feito',{exact:true}).fill('Pavimento reparado, aguardando envio da foto.');
 await field.getByRole('button',{name:'Enviar para análise',exact:true}).click();
 const missingPhoto=field.getByRole('alert').filter({hasText:'Anexe uma foto depois do serviço.'});
 await missingPhoto.waitFor();
 assert.equal(await missingPhoto.evaluate(el=>document.activeElement===el),true,'Submission error must receive focus');
 assert.equal(await missingPhoto.evaluate(el=>{const r=el.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight}),true,'Submission error must be visible on mobile');
 await field.getByLabel('Foto depois',{exact:true}).setInputFiles(photo);await field.getByRole('button',{name:'Enviar foto depois',exact:true}).click();
 await field.getByAltText('Foto depois do serviço',{exact:true}).waitFor();
 await field.getByLabel('O que foi feito',{exact:true}).fill('Pavimento reparado, via limpa e sinalização recolhida.');
 await field.screenshot({path:'test-results/field-execution.png',fullPage:true});
 assert.equal(await field.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await field.getByRole('button',{name:'Enviar para análise',exact:true}).click();await field.getByText('Resultado enviado. Aguarde a análise da gestão para o fechamento.',{exact:true}).waitFor();
 assert.equal(await field.getByRole('button',{name:'Validar e concluir',exact:true}).count(),0);
 await admin.reload();await admin.locator('nav').getByRole('button',{name:'Análise de campo',exact:true}).click();await admin.locator('.team-card').filter({hasText:order.code}).getByRole('button',{name:'Analisar ordem',exact:true}).click();
 await admin.getByRole('button',{name:/^Evidências/}).click();await admin.screenshot({path:'test-results/field-manager-review.png',fullPage:true});
 await admin.getByRole('button',{name:'Execução',exact:true}).click();await admin.getByRole('button',{name:'Validar e concluir',exact:true}).click();
 await admin.getByRole('dialog').getByText('Concluída',{exact:true}).first().waitFor();
 await field.getByRole('button',{name:'Atualizar tarefas',exact:true}).click();await field.getByText('Serviço aprovado por',{exact:false}).waitFor();
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({field:'390x844',manager:'1440x1000',draftRestored:true,photoRetryWithoutDuplicate:true,individualAssignment:true,reviewCompleted:true,consoleErrors:errors},null,2));
} finally {await browser.close();await new Promise(r=>server.close(r));await db.close();rmSync(temp,{recursive:true,force:true});}
