import { useState } from "react";
import "./inventory.css";
import { FileCheck2, FileText, Plus, Trash2, Upload } from "lucide-react";

const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value || 0);
const stageLabels: Record<string, string> = { registro: "Registro", triagem: "Triagem e planejamento", execucao: "Execução", validacao: "Validação", outros: "Outros" };
const emptyItem = () => ({ description: "", material_id: null, stage: "execucao", purchased_quantity: 1, used_quantity: 0, unit: "UN", unit_value: 0, product_total: 0 });

export default function InvoicePanel({ order, materials, api, onChange, canManage }: { order: any; materials: any[]; api: (path: string, method?: string, body?: any) => Promise<any>; onChange: () => Promise<void>; canManage: boolean }) {
  const [file, setFile] = useState<File | null>(null), [draft, setDraft] = useState<any>(() => order.invoices?.find((item: any) => item.status === "RASCUNHO") || null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const changeItem = (index: number, key: string, value: any) => setDraft({ ...draft, items: draft.items.map((item: any, position: number) => position === index ? { ...item, [key]: value, ...(key === "unit_value" || key === "purchased_quantity" ? { product_total: key === "unit_value" ? value * item.purchased_quantity : value * item.unit_value } : {}) } : item) });
  const allocated = (draft?.items || []).reduce((sum: number, item: any) => sum + Number(item.used_quantity || 0) * Number(item.unit_value || 0), 0);
  return <div className="invoice-panel">
    {error && <p className="form-error">{error}</p>}
    <div className="cost-stage-grid">{Object.entries(stageLabels).map(([key, label]) => <article key={key}><small>{label}</small><strong>{money((order.cost_by_stage || []).find((row: any) => row.stage === key)?.value || 0)}</strong></article>)}</div>
    <p className="muted">O custo por etapa soma as aplicações diretas da NF e as baixas de materiais registradas durante a execução. O restante permanece no estoque.</p>
    <div className="invoice-list">{(order.invoices || []).filter((item: any) => item.status === "CONFIRMADA").map((invoice: any) => <a key={invoice.id} href={`/api/notas-fiscais/${invoice.id}/arquivo`} target="_blank" rel="noreferrer"><FileCheck2/><span><strong>NF {invoice.invoice_number} · {invoice.supplier}</strong><small>{invoice.issue_date || "Data não informada"} · {money(invoice.total_value)}</small></span></a>)}</div>
    {canManage && !draft && <form className="invoice-upload" onSubmit={async (event) => { event.preventDefault(); if (!file) return; setBusy(true); setError(""); try { const body = new FormData(); body.append("file", file); setDraft(await api(`/ordens-servico/${order.id}/notas-fiscais/extrair`, "POST", body)); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}><FileText size={26}/><div><strong>Vincular nota fiscal em PDF</strong><small>O sistema lê o texto e monta um rascunho. Confira tudo antes do lançamento.</small></div><input required type="file" accept="application/pdf" onChange={(e) => setFile(e.target.files?.[0] || null)}/><button className="button primary" disabled={busy}><Upload size={16}/>{busy ? "Lendo PDF..." : "Ler nota"}</button></form>}
    {draft && <form className="invoice-review" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(""); try { await api(`/notas-fiscais/${draft.id}/confirmar`, "POST", { supplier: draft.supplier, invoice_number: draft.invoice_number, issue_date: draft.issue_date || null, total_value: Number(draft.total_value), items: draft.items.map(({ description, material_id, stage, purchased_quantity, used_quantity, unit, unit_value, product_total }: any) => ({ description, material_id: material_id || null, stage, purchased_quantity: Number(purchased_quantity), used_quantity: Number(used_quantity), unit, unit_value: Number(unit_value), product_total: Number(product_total) })) }); setDraft(null); await onChange(); } catch (e: any) { setError(e.message); } finally { setBusy(false); } }}>
      <div className={`extraction-note ${draft.extraction_status}`}><strong>{draft.extraction_status === "itens_encontrados" ? "Leitura concluída" : draft.extraction_status === "sem_texto" ? "PDF sem texto pesquisável" : "Conferência manual necessária"}</strong><span>{draft.extraction_status === "itens_encontrados" ? "Confira os dados extraídos antes de confirmar." : "Inclua ou corrija os itens usando a nota aberta ao lado."}</span><a href={`/api/notas-fiscais/${draft.id}/arquivo`} target="_blank" rel="noreferrer">Abrir PDF</a></div>
      <div className="form-grid"><label>Fornecedor<input required value={draft.supplier} onChange={(e) => setDraft({ ...draft, supplier: e.target.value })}/></label><label>Número da NF<input required value={draft.invoice_number} onChange={(e) => setDraft({ ...draft, invoice_number: e.target.value })}/></label><label>Emissão<input type="date" value={draft.issue_date || ""} onChange={(e) => setDraft({ ...draft, issue_date: e.target.value })}/></label><label>Valor total<input required min="0" step="0.01" type="number" value={draft.total_value} onChange={(e) => setDraft({ ...draft, total_value: Number(e.target.value) })}/></label></div>
      <div className="table-scroll"><table className="invoice-items"><thead><tr><th>Produto</th><th>Material do estoque</th><th>Qtd. comprada</th><th>Qtd. aplicada nesta OS</th><th>Un.</th><th>Valor unit.</th><th>Total</th><th>Etapa do gasto</th><th/></tr></thead><tbody>{draft.items.map((item: any, index: number) => <tr key={item.id || index}><td><input required value={item.description} onChange={(e) => changeItem(index, "description", e.target.value)}/></td><td><select value={item.material_id || ""} onChange={(e) => changeItem(index, "material_id", e.target.value || null)}><option value="">Não vinculado</option>{materials.map((material) => <option key={material.id} value={material.id}>{material.name}</option>)}</select></td><td><input required min="0.001" step="0.001" type="number" value={item.purchased_quantity} onChange={(e) => changeItem(index, "purchased_quantity", Number(e.target.value))}/></td><td><input required min="0" max={item.purchased_quantity} step="0.001" type="number" value={item.used_quantity} onChange={(e) => changeItem(index, "used_quantity", Number(e.target.value))}/></td><td><input required value={item.unit} onChange={(e) => changeItem(index, "unit", e.target.value)}/></td><td><input required min="0" step="0.0001" type="number" value={item.unit_value} onChange={(e) => changeItem(index, "unit_value", Number(e.target.value))}/></td><td>{money(item.product_total)}</td><td><select value={item.stage} onChange={(e) => changeItem(index, "stage", e.target.value)}>{Object.entries(stageLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></td><td><button type="button" className="icon" title="Remover item" onClick={() => setDraft({ ...draft, items: draft.items.filter((_: any, position: number) => position !== index) })}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>
      <div className="invoice-actions"><button type="button" className="button secondary" onClick={() => setDraft({ ...draft, items: [...draft.items, emptyItem()] })}><Plus size={16}/>Adicionar item</button><span><small>Custo alocado nesta OS</small><strong>{money(allocated)}</strong></span><button className="button primary" disabled={busy || !draft.items.length}><FileCheck2 size={16}/>{busy ? "Confirmando..." : "Confirmar NF e lançar estoque"}</button></div>
    </form>}
  </div>;
}
